# Generated by Django 2.2.5 on 2019-10-09 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
