# Generated by Django 3.1.2 on 2020-10-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191009_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lead',
            field=models.TextField(),
        ),
    ]
