# Generated by Django 2.1.7 on 2019-08-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imageload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageLoad',
            new_name='Imagee',
        ),
    ]
